import Head from "next/head";
import Link from "next/link";
import Login from "~/components/Login";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex w-[100vw] bg-base font-montserrat">
				<div className="flex h-screen min-w-[40vw] items-center justify-center bg-black text-7xl font-bold text-white">
					<h1>Board.</h1>
				</div>
				<Login />
			</main>
		</>
	);
}
