import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useAuthState } from "react-firebase-hooks/auth";
import Login from "~/components/Login";
import { auth } from "~/config";

export default function Home() {
	const [user, loading] = useAuthState(auth);
	const router = useRouter();
	if (loading) {
		return <h1>Loading...</h1>;
	}
	if (user) {
		router.push("/");
	}

	return (
		<>
			<Head>
				<title>Listed</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="margin-0 padding-0 flex h-full w-full bg-base font-montserrat">
				<div className="flex min-h-[99vh] min-w-[40vw] items-center justify-center bg-black text-7xl font-bold text-white">
					<h1>Board.</h1>
				</div>
				<Login />
			</main>
		</>
	);
}
