import MainGraph from "~/components/MainGraph";
import Navbar from "~/components/Navbar";
import PieGraph from "~/components/PieGraph";
import Schedule from "~/components/Schedule";
import SearchBar from "~/components/SearchBar";
import StatusCardsContainer from "~/components/StatusCardsContainer";
import { useRouter } from "next/router";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "~/config";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home({ lineGraph }: any) {
	const [user, loading] = useAuthState(auth);

	const [GuestsLineGraph, setGuestsLineGraph] = useState([100]);

	const router = useRouter();
	if (loading) {
		return <h1>Loading...</h1>;
	}
	if (!user) {
		router.push("/auth");
	} else {
		return (
			<>
				<Head>
					<title>Listed</title>
					<meta name="description" content="Generated by create-t3-app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main className="relative flex min-h-screen min-w-full bg-base p-[2.5vw] font-montserrat">
					<Navbar />
					<div className="w-[74.5vw] p-8">
						<SearchBar />
						<StatusCardsContainer />
						<MainGraph lineGraph={setGuestsLineGraph} />
						<div className="my-4 flex gap-[40px] rounded-[40px]">
							<PieGraph />
							<Schedule />
						</div>
					</div>
				</main>
			</>
		);
	}
}

export async function getServerSideProps() {
	const url =
		"https://firestore.googleapis.com/v1/projects/grocare-7442b/databases/(default)/documents/users/line-graph-data";

	const data = await fetch(url)
		.then((response) => {
			return response.json();
		})
		// .then((json) => {
		// 	return FireStoreParser(json);
		// });

	return {
		props: {
			lineGraph: data,
		},
	};
}
