import Head from "next/head";
import Link from "next/link";
import MainGraph from "~/components/MainGraph";
import Navbar from "~/components/Navbar";
import PieGraph from "~/components/PieGraph";
import Schedule from "~/components/Schedule";
import SearchBar from "~/components/SearchBar";
import StatusCards from "~/components/StatusCards";
import StatusCardsContainer from "~/components/StatusCardsContainer";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="relative flex min-h-screen min-w-[100vw] gap-8 bg-base p-10 font-montserrat">
				<Navbar />
				<div className="w-full p-4">
					<SearchBar />
					<StatusCardsContainer />
					<MainGraph />
					<div className="flex gap-4">
						<PieGraph />
						<Schedule />
					</div>
				</div>
			</main>
		</>
	);
}
